# Build the project and publish it on Modrinth

name: publish
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: setup jdk 16
        uses: actions/setup-java@v1
        with:
          java-version: 16
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: publish on modrinth
        run: ./gradlew publishModrinth
